# Google Cloud Build configuration for MinberAI
# This file enables automated CI/CD with Cloud Build
# 
# Note: Environment variables should be set in Cloud Build trigger configuration
# Required substitutions:
# - _REGION (default: europe-west1)
# - _SERVICE_NAME_PROD (default: minbarai-pro)
# - _SERVICE_NAME_DEV (default: minbarai-dev)
# - _CUSTOM_DOMAIN (default: minbarai.com)

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/minberai:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/minberai:latest',
      '.'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/minberai:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/minberai:latest']

  # Deploy to Cloud Run (Production)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME_PROD}',
      '--image', 'gcr.io/$PROJECT_ID/minberai:$COMMIT_SHA',
      '--platform', 'managed',
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--min-instances', '1',
      '--max-instances', '50',
      '--concurrency', '100',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=production',
      '--set-env-vars', 'NEXT_PUBLIC_SITE_URL=https://${_CUSTOM_DOMAIN}',
      '--set-env-vars', 'NEXTAUTH_URL=https://${_CUSTOM_DOMAIN}',
      '--set-secrets', 'STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest',
      '--set-secrets', 'STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest',
      '--set-secrets', 'SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest',
      '--service-account', 'minberai-service-account@$PROJECT_ID.iam.gserviceaccount.com',
      '--quiet'
    ]

  # Deploy to Cloud Run (Development)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME_DEV}',
      '--image', 'gcr.io/$PROJECT_ID/minberai:$COMMIT_SHA',
      '--platform', 'managed',
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--concurrency', '100',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=development',
      '--set-secrets', 'STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest',
      '--set-secrets', 'STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest',
      '--set-secrets', 'SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest',
      '--service-account', 'minberai-service-account@$PROJECT_ID.iam.gserviceaccount.com',
      '--quiet'
    ]

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitution variables
substitutions:
  _REGION: 'europe-west1'
  _SERVICE_NAME_PROD: 'minbarai-pro'
  _SERVICE_NAME_DEV: 'minbarai-dev'
  _CUSTOM_DOMAIN: 'minbarai.com'

# Build triggers configuration
# To set up automatic builds, run:
# gcloud builds triggers create github \
#   --repo-name=MinberAI-core \
#   --repo-owner=your-github-username \
#   --branch-pattern="^main$" \
#   --build-config=cloudbuild.yaml
